version: 2
jobs:
  build:
    docker:
      - image: jongleberry/docker-nodejs-postgres:latest
        environment:
          DATABASE_URL: postgres://pgrole:pgrole@localhost/pgdb?sslmode=disable
          DATABASE_NAME: pgdb
    working_directory: ~/vacation-server
    steps:
      - checkout
      - run: dropdb pgdb --if-exists
      - run: createdb pgdb
      - run: psql -d pgdb -c "CREATE EXTENSION IF NOT EXISTS postgis; CREATE EXTENSION IF NOT EXISTS citext; CREATE EXTENSION IF NOT EXISTS pgcrypto;"
